#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AudiosAmigo.Droid.Resource", IsApplication=true)]

namespace AudiosAmigo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int bgdarker = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int audiosrv = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bgmain = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int empty_vdivider = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hdivider = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int mute = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int muteblue = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int thumb = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int thumb_small = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int vdivider = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int connect = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int device_container = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int disconnect = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int image = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int ip = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int ip_address = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int list = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int master_sliders = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int normal_sliders = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int password = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int port = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int process_image = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int seek_bar = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int seek_bar_holder = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int slider_scroll = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int status = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int system_sliders = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int connect_menu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_selector = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int volume_slider = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
