#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AudiosAmigo.Droid.Resource", IsApplication=true)]

namespace AudiosAmigo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int audiosrv = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_connect_menu = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bgmain = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int empty_vdivider = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hdivider = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mute = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int muteblue = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int thumb = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int thumb_small = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int vdivider = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int connect = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int device_container = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int disconnect = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int image = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int ip = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int ip_address = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int master_sliders = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int normal_sliders = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int password = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int port = 2131034113;
			
			// aapt resource value: 0x7f050012
			public const int process_image = 2131034130;
			
			// aapt resource value: 0x7f050005
			public const int save = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int save_list = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int search = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int search_list = 2131034119;
			
			// aapt resource value: 0x7f050014
			public const int seek_bar = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int seek_bar_holder = 2131034131;
			
			// aapt resource value: 0x7f05000b
			public const int slider_scroll = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int status = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int system_sliders = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int welcome = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int connect_menu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_selector = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int volume_slider = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int connect_menu_connect_text = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int connect_menu_ip_hint = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int connect_menu_password_hint = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int connect_menu_port_hint = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int connect_menu_save_list_text = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int connect_menu_save_text = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int connect_menu_search_list_text = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int connect_menu_search_text = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int connect_menu_welcome_message = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int preference_save_file_key = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
