#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AudiosAmigo.Droid.Resource", IsApplication=true)]

namespace AudiosAmigo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int adSize = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int adSizes = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int adUnitId = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int audiosrv = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_connect_menu = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bgmain = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int empty_vdivider = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hdivider = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mute = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int muteblue = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int thumb = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int thumb_small = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int vdivider = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070015
			public const int adView = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int adjust_height = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int adjust_width = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int connect = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int device_container = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int disconnect = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int image = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int ip = 2131165187;
			
			// aapt resource value: 0x7f070013
			public const int ip_address = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int master_sliders = 2131165200;
			
			// aapt resource value: 0x7f070002
			public const int none = 2131165186;
			
			// aapt resource value: 0x7f07000f
			public const int normal_sliders = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int password = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int port = 2131165188;
			
			// aapt resource value: 0x7f070016
			public const int process_image = 2131165206;
			
			// aapt resource value: 0x7f070008
			public const int save = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int save_list = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int search = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int search_list = 2131165194;
			
			// aapt resource value: 0x7f070018
			public const int seek_bar = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int seek_bar_holder = 2131165207;
			
			// aapt resource value: 0x7f07000e
			public const int slider_scroll = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int status = 2131165204;
			
			// aapt resource value: 0x7f070011
			public const int system_sliders = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int welcome = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int connect_menu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_selector = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int volume_slider = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040009
			public const int ApplicationName = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int accept = 2130968581;
			
			// aapt resource value: 0x7f040017
			public const int admob_adUnitId = 2130968599;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040016
			public const int connect_menu_confirm_delete_msg = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int connect_menu_confirm_delete_neg = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int connect_menu_confirm_delete_pos = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int connect_menu_confirm_delete_title = 2130968595;
			
			// aapt resource value: 0x7f04000e
			public const int connect_menu_connect_text = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int connect_menu_ip_hint = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int connect_menu_password_hint = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int connect_menu_port_hint = 2130968587;
			
			// aapt resource value: 0x7f040012
			public const int connect_menu_save_list_text = 2130968594;
			
			// aapt resource value: 0x7f04000f
			public const int connect_menu_save_text = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int connect_menu_search_list_text = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int connect_menu_search_text = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int connect_menu_welcome_message = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int create_calendar_message = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int create_calendar_title = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int decline = 2130968582;
			
			// aapt resource value: 0x7f040018
			public const int preference_save_file_key = 2130968600;
			
			// aapt resource value: 0x7f040004
			public const int store_picture_message = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int store_picture_title = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_IAPTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
